//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpFn { get; set; }
        public string EmpLn { get; set; }
        public string EmpAddress { get; set; }
        public string EmpPhno { get; set; }
        public string Gender { get; set; }
    }
}
